-- Gerado a partir de Pasta1.xlsx
-- Atualiza username_nuvidio e username_0800 localizando pelo nome do operador
BEGIN TRANSACTION;
UPDATE local_portal_users SET username_nuvidio = 'adriellecassemiro@krservices.com.br', username_0800 = 'ADRIELLE DE MOURA CASSEMIRO', updated_at = CURRENT_TIMESTAMP WHERE name = 'Adrielle de Moura Cassemiro';
UPDATE local_portal_users SET username_nuvidio = 'aline.gregorio@krservices.com.br', username_0800 = 'ALINE RODRIGUES GREGORIO', updated_at = CURRENT_TIMESTAMP WHERE name = 'Aline Rodrigues Gregorio';
UPDATE local_portal_users SET username_nuvidio = 'ana.carneiro@krservices.com.br', username_0800 = 'ANA BEATRIZ CARNEIRO DE SOUZA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Ana Beatriz Carneiro de Souza';
UPDATE local_portal_users SET username_nuvidio = 'ana.castro@krservices.com.br', username_0800 = 'ANA CLARA DE CASTRO NASCIMENTO', updated_at = CURRENT_TIMESTAMP WHERE name = 'Ana Clara de Castro Nascimento';
UPDATE local_portal_users SET username_nuvidio = 'ana.lina@krservices.com.br', username_0800 = 'ANA JULIA LINA SILVA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Ana Julia Lina Silva';
UPDATE local_portal_users SET username_nuvidio = 'ana.damasceno@krservices.com.br', username_0800 = 'ANA PAULA DAMASCENO SILVA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Ana Paula Damasceno Silva';
UPDATE local_portal_users SET username_nuvidio = 'bianca.duarte@krservices.com.br', username_0800 = 'BIANCA LETICIA SANTOS DUARTE', updated_at = CURRENT_TIMESTAMP WHERE name = 'Bianca Leticia Santos Duarte';
UPDATE local_portal_users SET username_nuvidio = 'cattarina.amaral@krservices.com.br', username_0800 = 'CATTARINA PIORNEDO MENEZES DO AMARAL', updated_at = CURRENT_TIMESTAMP WHERE name = 'Cattarina Piornedo Menezes do Amaral';
UPDATE local_portal_users SET username_nuvidio = 'caua.oliveira@krservices.com.br', username_0800 = 'CAUA LUCAS LOPES DE LIMA OLIVEIRA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Caua Lucas Lopes de Lima Oliveira';
UPDATE local_portal_users SET username_nuvidio = 'daphyne.silva@krservices.com.br', username_0800 = 'DAPHYNE BEATRIZ ROCHA SILVA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Daphyne Beatriz Rocha Silva';
UPDATE local_portal_users SET username_nuvidio = 'diego.lopes@krservices.com.br', username_0800 = 'DIEGO LUIZ FERR', updated_at = CURRENT_TIMESTAMP WHERE name = 'Diego Luiz Ferreira Lopes';
UPDATE local_portal_users SET username_nuvidio = 'edneia.pereira@krservices.com.br', username_0800 = NULL, updated_at = CURRENT_TIMESTAMP WHERE name = 'Edneia dos Reis Pereira Boaventura';
UPDATE local_portal_users SET username_nuvidio = 'floresto.neto@krservices.com.br', username_0800 = NULL, updated_at = CURRENT_TIMESTAMP WHERE name = 'Floresto Scarpelli Neto';
UPDATE local_portal_users SET username_nuvidio = 'gabriela.cruz@krservices.com.br', username_0800 = 'GABRIELA CARINHANHA DA CRUZ', updated_at = CURRENT_TIMESTAMP WHERE name = 'Gabriela Carinhanha da Cruz';
UPDATE local_portal_users SET username_nuvidio = 'gislaine.goncalves@krservices.com.br', username_0800 = 'GISLAINE GARCIA MOREIRA GONCALVES', updated_at = CURRENT_TIMESTAMP WHERE name = 'Gislaine Garcia Moreira Gonçalves';
UPDATE local_portal_users SET username_nuvidio = 'guilherme.oliveira@krservices.com.br', username_0800 = 'GUILHERME HENRIQUE DE OLIVEIRA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Guilherme Henrique de Oliveira';
UPDATE local_portal_users SET username_nuvidio = 'heoisa.moreira@krservices.com.br', username_0800 = NULL, updated_at = CURRENT_TIMESTAMP WHERE name = 'Heloisa Lopes Moreira';
UPDATE local_portal_users SET username_nuvidio = 'hillary.ribeiro@krservices.com.br', username_0800 = NULL, updated_at = CURRENT_TIMESTAMP WHERE name = 'Hillary Ester Machado Ribeiro';
UPDATE local_portal_users SET username_nuvidio = 'hugo.piders@krservices.com.br', username_0800 = 'HUGO OLIVEIRA SALOME PIDERS', updated_at = CURRENT_TIMESTAMP WHERE name = 'Hugo Oliveira Salomé Piders';
UPDATE local_portal_users SET username_nuvidio = 'igor.silva@krservices.com.br', username_0800 = NULL, updated_at = CURRENT_TIMESTAMP WHERE name = 'Igor Lucas Faria Silva';
UPDATE local_portal_users SET username_nuvidio = 'ingrid.ferreira@krservices.com.br', username_0800 = 'INGRID ROBERTA SILVA FERREIRA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Ingrid Roberta Silva Ferreira';
UPDATE local_portal_users SET username_nuvidio = 'ipe.oliveira@krservices.com.br', username_0800 = 'IPE CHAGAS DE OLIVEIRA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Ipê Chagas de Oliveira';
UPDATE local_portal_users SET username_nuvidio = 'izabela.neves@krservices.com.br', username_0800 = 'IZABELA CRISTINA DE SOUZA NEVES', updated_at = CURRENT_TIMESTAMP WHERE name = 'Izabela Cristina de Souza Neves';
UPDATE local_portal_users SET username_nuvidio = 'janderson.silva@krservices.com.br', username_0800 = 'JANDERSON ANDRE PEREIRA DA SILVA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Janderson André Pereira da Silva';
UPDATE local_portal_users SET username_nuvidio = 'jennifer.pereira@krservices.com.br', username_0800 = 'JENNIFER KELLY DIAS PEREIRA EUGENIO', updated_at = CURRENT_TIMESTAMP WHERE name = 'Jennifer Kelly Dias Pereira';
UPDATE local_portal_users SET username_nuvidio = 'jessicabar@krservices.com.br', username_0800 = 'JESSICA PATRICIA GONCALVES BARBOSA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Jessica Patricia Gonçalves Barbosa';
UPDATE local_portal_users SET username_nuvidio = 'jhennifer.soares@krservices.com.br', username_0800 = 'JHENNIFER ALESSANDRA SOARES', updated_at = CURRENT_TIMESTAMP WHERE name = 'Jhennifer Alessandra Soares';
UPDATE local_portal_users SET username_nuvidio = 'joao.ferreira@krservices.com.br', username_0800 = 'JOAO VICTOR FERREIRA', updated_at = CURRENT_TIMESTAMP WHERE name = 'João Victor Ferreira';
UPDATE local_portal_users SET username_nuvidio = 'josilene.oliveira@krserivces.com.br', username_0800 = 'JOSILENE APARECIDA DE OLIVEIRA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Josilene Aparecida de Oliveira';
UPDATE local_portal_users SET username_nuvidio = 'juliane.melo@krservices.com.br', username_0800 = 'JULIANE SETE DE ABRIL MELO', updated_at = CURRENT_TIMESTAMP WHERE name = 'Juliane Sete de Abril Melo';
UPDATE local_portal_users SET username_nuvidio = 'junia.ferreira@krservices.com.br', username_0800 = 'JUNIA CRISTINA FERREIRA GONCALO', updated_at = CURRENT_TIMESTAMP WHERE name = 'Junia Cristina Ferreira Gonçalo';
UPDATE local_portal_users SET username_nuvidio = 'leticia.perche@krservices.com.br', username_0800 = 'LETICIA RAFAELA PERCHE', updated_at = CURRENT_TIMESTAMP WHERE name = 'Leticia Rafaela Perche';
UPDATE local_portal_users SET username_nuvidio = 'lorrainny.murici@krservices.com.br', username_0800 = 'LORRAINNY DOS SANTOS MURICI', updated_at = CURRENT_TIMESTAMP WHERE name = 'Lorrainny dos Santos Murici';
UPDATE local_portal_users SET username_nuvidio = 'luana.lima@krservices.com.br', username_0800 = 'LUANA FLAVIA PEREIRA DE LIMA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Luana Flavia Pereira de Lima';
UPDATE local_portal_users SET username_nuvidio = 'lucilene.campos@krservices.com.br', username_0800 = 'LUCILENE RIBEIRO CAMPOS', updated_at = CURRENT_TIMESTAMP WHERE name = 'Lucilene Ribeiro Campos';
UPDATE local_portal_users SET username_nuvidio = 'marcelle.aparecida@krservices.com.br', username_0800 = 'MARCELLE APARECIDA DA SILVA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Marcelle Aparecida da Silva';
UPDATE local_portal_users SET username_nuvidio = 'maria.silva@krservices.com.br', username_0800 = 'MARIA EDUARDA F', updated_at = CURRENT_TIMESTAMP WHERE name = 'Maria Eduarda Guimaraes Silva';
UPDATE local_portal_users SET username_nuvidio = 'maria.falconi@krservices.com.br', username_0800 = 'MARIA LUIZA DE SOUZA FALCONI', updated_at = CURRENT_TIMESTAMP WHERE name = 'Maria Luiza de Souza Falconi';
UPDATE local_portal_users SET username_nuvidio = 'marilene.ribeiro@krservices.com.br', username_0800 = 'MARILENE MENDES RIBEIRO', updated_at = CURRENT_TIMESTAMP WHERE name = 'Marilene Mendes Ribeiro';
UPDATE local_portal_users SET username_nuvidio = 'marina.martins@krservices.com.br', username_0800 = 'MARINA DA SILVA MARTINS', updated_at = CURRENT_TIMESTAMP WHERE name = 'Marina da Silva Martins';
UPDATE local_portal_users SET username_nuvidio = 'mateus.melo@krservices.com.br', username_0800 = 'MATEUS HENRIQUE JORGE DE MELO', updated_at = CURRENT_TIMESTAMP WHERE name = 'Mateus Henrique Jorge de Melo';
UPDATE local_portal_users SET username_nuvidio = 'matheus.abreu@krservices.com.br', username_0800 = 'MATHEUS DIAS SI', updated_at = CURRENT_TIMESTAMP WHERE name = 'Matheus Dias Silva de Abreu';
UPDATE local_portal_users SET username_nuvidio = 'maysa.ferreira@krservices.com.br', username_0800 = NULL, updated_at = CURRENT_TIMESTAMP WHERE name = 'Maysa Eduarda Alves Ferreira';
UPDATE local_portal_users SET username_nuvidio = 'midyan.silva@krservices.com.br', username_0800 = 'MIDYAN SILVA COELHO', updated_at = CURRENT_TIMESTAMP WHERE name = 'Midyan Silva Coelho';
UPDATE local_portal_users SET username_nuvidio = 'miriene.garcia@krservices.com.br', username_0800 = 'MIRIENE CAMILLY GARCIA DA SILVA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Miriene Camilly Garcia da Silva';
UPDATE local_portal_users SET username_nuvidio = 'nathali.reis@krservices.com.br', username_0800 = 'NATHALI VITORIA DE OLIVEIRA GONCALVES DO', updated_at = CURRENT_TIMESTAMP WHERE name = 'Nathali Vitória de Oliveira Gonçalves dos Reis';
UPDATE local_portal_users SET username_nuvidio = 'pamela.lopes@krservices.com.br', username_0800 = 'PAMELA KARINA LOPES DE LIMA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Pamela Karina Lopes de Lima';
UPDATE local_portal_users SET username_nuvidio = 'pamella.crispim@krservices.com.br', username_0800 = 'PAMELLA PEREIRA CRISPIM', updated_at = CURRENT_TIMESTAMP WHERE name = 'Pamella Pereira Crispim';
UPDATE local_portal_users SET username_nuvidio = 'poliane.silva@krservices.com.br', username_0800 = NULL, updated_at = CURRENT_TIMESTAMP WHERE name = 'Poliana Ribeiro Silva';
UPDATE local_portal_users SET username_nuvidio = 'rayssa.silva@krservices.com.br', username_0800 = 'RAYSSA CAMILE DOS SANTOS SILVA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Rayssa Camile dos Santos Silva';
UPDATE local_portal_users SET username_nuvidio = 'rayssa.batista@krservices.com.br', username_0800 = NULL, updated_at = CURRENT_TIMESTAMP WHERE name = 'Rayssa Lorraine Fernandes Batista';
UPDATE local_portal_users SET username_nuvidio = 'ryan.barbosa@krservices.com.br', username_0800 = 'RYAN BARBOSA SILVA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Ryan Barbosa Silva';
UPDATE local_portal_users SET username_nuvidio = 'sara.batista@krservices.com.br', username_0800 = 'SARA DOS SANTOS BATISTA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Sara dos Santos Batista';
UPDATE local_portal_users SET username_nuvidio = 'sarah.oliveira@krservices.com.br', username_0800 = 'SARAH DANTAS DE OLIVEIRA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Sarah Dantas de Oliveira';
UPDATE local_portal_users SET username_nuvidio = 'sarah.lima@krservices.com.br', username_0800 = 'SARAH DE FREITA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Sarah de Freitas Lima';
UPDATE local_portal_users SET username_nuvidio = 'suelen.cruz@krservices.com.br', username_0800 = NULL, updated_at = CURRENT_TIMESTAMP WHERE name = 'Suelen Santos Cruz';
UPDATE local_portal_users SET username_nuvidio = 'taline.almeida@krservices.com.br', username_0800 = NULL, updated_at = CURRENT_TIMESTAMP WHERE name = 'Taline Mara Teixeira Almeida';
UPDATE local_portal_users SET username_nuvidio = 'talita.carvalho@krservices.com.br', username_0800 = 'TALITA EMANUELE DIAS CARVALHO', updated_at = CURRENT_TIMESTAMP WHERE name = 'Talita Emanuele Dias Carvalho';
UPDATE local_portal_users SET username_nuvidio = 'tawanya.salustiano@krservices.com.br', username_0800 = NULL, updated_at = CURRENT_TIMESTAMP WHERE name = 'Tawanya Tayna Dutra Salustiano';
UPDATE local_portal_users SET username_nuvidio = 'taynan.moreira@krservices.com.br', username_0800 = 'TAYNAN DIESSICA MOREIRA DE SA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Taynan Diessica Moreira de Sá';
UPDATE local_portal_users SET username_nuvidio = 'thaina.santos@krservices.com.br', username_0800 = 'THAINA PIRES DOS SANTOS', updated_at = CURRENT_TIMESTAMP WHERE name = 'Thaina Pires dos Santos';
UPDATE local_portal_users SET username_nuvidio = 'thais.souza@krservices.com.br', username_0800 = NULL, updated_at = CURRENT_TIMESTAMP WHERE name = 'Thais Ferreira de Souza';
UPDATE local_portal_users SET username_nuvidio = 'vanusa.campos@krservices.com.br', username_0800 = 'VANUSA LEITE CAMPOS', updated_at = CURRENT_TIMESTAMP WHERE name = 'Vanusa Leite Campos';
UPDATE local_portal_users SET username_nuvidio = 'victor.ribeiro@krservices.com.br', username_0800 = 'VICTOR MATHEUS RIBEIRO DA SILVA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Victor Matheus Ribeiro da Silva';
UPDATE local_portal_users SET username_nuvidio = 'vitoria.caetano@krservices.com.br', username_0800 = 'VITORIA APARECIDA CAETANO NEVES', updated_at = CURRENT_TIMESTAMP WHERE name = 'Vitória Aparecida Caetano Neves';
UPDATE local_portal_users SET username_nuvidio = 'viviane.moura@krservices.com.br', username_0800 = 'VIVIANE VIEIRA', updated_at = CURRENT_TIMESTAMP WHERE name = 'Viviane Vieira de Moura';
COMMIT;
